name: zs-yaml CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Set version
        id: set_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=$(python setup.py --version)
          else
            VERSION=$(python setup.py --version).dev0
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          sed -i "s/__version__ = .*/__version__ = '${VERSION}'/" zs_yaml/_version.py
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.KE_PYPI_TOKEN }}
        run: |
          twine check dist/*
          twine upload dist/*
